default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: digesto_dev
  username: postgres
  password: metallica22
  host: localhost


production:
  <<: *default
  database: digesto_prod
  username: postgres
  password: metallica22
  host: localhost

