# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
  branches = Branch.create([
  			{name: 'I - Administrativo', number: 1},
			{name: 'II - Comercio y Promoción Industrial',number: 2},
			{name: 'III - Cultura y Educación',number: 3},
			{name: 'IV - Deporte, Recreación y Turismo',number: 4},
			{name: 'V - Financiero',number: 5},
			{name: 'VI - Medio Ambiente y Recursos Naturales',number: 6},
			{name: 'VII - Medios de Comunicación Social',number: 7},
			{name: 'VIII - MERCOSUR e Integración Regional',number: 8},
			{name: 'IX - Particulares',number: 9},
			{name: 'X - Policía Municipal',number: 10},
			{name: 'XI - Público Municipal',number: 11},
			{name: 'XII - Salud y Calidad de Vida',number: 12},
			{name: 'XIII - Servicios Públicos',number: 13},
			{name: 'XIV - Tierras Fiscales',number: 14},
			{name: 'XV - Trabajo, Seguridad Social y Régimen Previsional',number: 15},
			{name: 'XVI - Transporte y Tránsito',number: 16},
			{name: 'XVII - Vivienda, Planificación Urbana y Obras Públicas',number:17},
			{name:"Normas No Consolidadas",number: 18},
			{name:"Normas Refundidas",number: 19}])
 #  	branch =Branch.find(1)
 #    branch.data_ordinances.create(title: 'Administrativo I - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.')
	# branch.data_ordinances.new(title: 'Administrativo I - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.')
	# branch.data_ordinances.new(title: 'Administrativo I - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación')
	# branch.data_ordinances.new(title: 'Administrativo I - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.')
	# branch.data_ordinances.new(title: 'Administrativo I - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con')
	# branch.data_ordinances.new(title: 'Administrativo I - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.')
	# branch.data_ordinances.new(title: 'Administrativo I - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.')
	# branch.data_ordinances.new(title: 'Administrativo I - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Organismos y dependencias municipales. Atención al público.')
	# branch.data_ordinances.new(title: 'Administrativo I - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.')
	# branch.data_ordinances.new(title: 'Administrativo I - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.')
	# branch.data_ordinances.new(title: 'Administrativo I - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación')
	# branch.data_ordinances.new(title: 'Administrativo I - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Junta Municipal de la Defensa Civil. Conformación.')
	# branch.data_ordinances.new(title: 'Administrativo I - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.')
	# branch.data_ordinances.new(title: 'Administrativo I - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.')
	# branch.data_ordinances.new(title: 'Administrativo I - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: Time.now, type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:Time.now , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: Time.now, general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.')
    
#   Mayor.create(name: 'Emanuel', city: cities.first)
# DataOrdinance.create([
# 		{branch_id: 1, title: 'Administrativo I - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 1, title: 'Administrativo I - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 1, title: 'Administrativo I - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 1, title: 'Administrativo I - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 1, title: 'Administrativo I - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 1, title: 'Administrativo I - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 1, title: 'Administrativo I - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 1, title: 'Administrativo I - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 1, title: 'Administrativo I - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 1, title: 'Administrativo I - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 1, title: 'Administrativo I - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 1, title: 'Administrativo I - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 1, title: 'Administrativo I - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 1, title: 'Administrativo I - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'},

		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 2, title: 'Comercio y Promoción Industrial II- 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'}	,	
	
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 3, title: 'Deporte, Recreación y Turismo III - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'}		,

		# {branch_id: 4, title: 'Financiero V - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 4, title: 'Financiero V - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 4, title: 'Financiero V - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 4, title: 'Financiero V - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 4, title: 'Financiero V - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 4, title: 'Financiero V - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 4, title: 'Financiero V - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 4, title: 'Financiero V - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 4, title: 'Financiero V - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 4, title: 'Financiero V - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 4, title: 'Financiero V - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 4, title: 'Financiero V - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 4, title: 'Financiero V - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 4, title: 'Financiero V - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'}		,

		# {branch_id: 18, title: 'Normas No Consolidadas - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 18, title: 'Normas No Consolidadas - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'}		,

		# {branch_id: 19, title: 'Normas Refundidas - 1', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Dirección General de Turismo Municipal. Creación. Funciones.'},
		# {branch_id: 19, title: 'Normas Refundidas - 2', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal de Villa Urquiza y Villa Lanús. Creación'},
		# {branch_id: 19, title: 'Normas Refundidas - 3', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación.'},
		# {branch_id: 19, title: 'Normas Refundidas - 4', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Denomina "Decreto de Ordenanza" a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con'},
		# {branch_id: 19, title: 'Normas Refundidas - 5', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal.'},
		# {branch_id: 19, title: 'Normas Refundidas - 6', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades.'},
		# {branch_id: 19, title: 'Normas Refundidas - 7', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Organismos y dependencias municipales. Atención al público.'},
		# {branch_id: 19, title: 'Normas Refundidas - 8', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional.'},
		# {branch_id: 19, title: 'Normas Refundidas - 9', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación.'},
		# {branch_id: 19, title: 'Normas Refundidas - 10', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación'},
		# {branch_id: 19, title: 'Normas Refundidas - 11', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Junta Municipal de la Defensa Civil. Conformación.'},
		# {branch_id: 19, title: 'Normas Refundidas - 12', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación.'},
		# {branch_id: 19, title: 'Normas Refundidas - 13', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado.'},
		# {branch_id: 19, title: 'Normas Refundidas - 14', description: '' , type_ordinance: '1', branch: '', number: '1' , previous_number: 1, date_sanction: '2016-06-08', type_bulletin:'1' , number_bulletin: 1, date_publication_bulletin:'2016-06-08' , page: 1 , type_promulgation: '1' , decree_promulgating: '1' , date_promulgation: '2016-06-08', general_theme: 'Jurado de Enjuiciamiento. Constitución y reglamentación.'}	
	#])

# {"title": "Administrativo I - 1", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Dirección General de Turismo Municipal. Creación. Funciones."},
# {"title": "Administrativo I - 2", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Delegación Municipal de Villa Urquiza y Villa Lanús. Creación"},
# {"title": "Administrativo I - 3", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Boletín Oficial de la Municipalidad de la Ciudad de Posadas. Creación."},
# {"title": "Administrativo I - 4", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Denomina Decreto de Ordenanza a todas aquellas dictadas desde el 28-06-1976 al 24-05-1973 y del 24-03-1976 al 10-12-1983. Establece la numeración correlativa de las Ordenanzas sancionadas por el Con"},
# {"title": "Administrativo I - 5", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Reglamento para la Substanciación de Sumarios Administrativos en ámbito del Departamento Municipal."},
# {"title": "Administrativo I - 6", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Delegación Municipal zona Península IPRODHA. Creación y regulación de facultades."},
# {"title": "Administrativo I - 7", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Organismos y dependencias municipales. Atención al público."},
# {"title": "Administrativo I - 8", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Establece en el ámbito de la Municipalidad de la Ciudad de Posadas la vigencia de la Fiscalía Municipal. Aprueba su Estatuto Funcional."},
# {"title": "Administrativo I - 9", "description": "" , "type_ordinance": "1", "branch": "", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Oficina Receptora de Reclamos y sugerencias del Contribuyente. Creación."},
# {"title": "Administrativo I - 10", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Registro de Instituciones de la Tercera Edad y/o Entidades que nuclean Jubilados y Pensionados. Creación"},
# {"title": "Administrativo I - 11", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Junta Municipal de la Defensa Civil. Conformación."},
# {"title": "Administrativo I - 12", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Constituye una Comisión Especial Ad Hoc para estudio y redacción de un nuevo Reglamento Organizativo y Funcional del Instituto de Medicina Física y Rehabilitación."},
# {"title": "Administrativo I - 13", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Determina la confección de talonarios utilizados por inspecciones municipales de las distintas áreas con boletas por triplicado."},
# {"title": "Administrativo I - 14", "description": ""  , "type_ordinance": "1", "branch": " ", "number": "1" , "previous_number": 1, "date_sanction": "2016-06-08", "type_bulletin":"1" , "number_bulletin": 1, "date_publication_bulletin":"2016-06-08" , "page": 1 , "type_promulgation": "1" , "decree_promulgating": "1" , "date_promulgation": "2016-06-08", "general_theme": "Jurado de Enjuiciamiento. Constitución y reglamentación."}